# Generated by Django 5.2.1 on 2025-08-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_post_user', 'New post by followed user'), ('new_post_hashtag', 'New post under followed hashtag'), ('new_post_uni', 'New post under followed university'), ('comment_on_my_post', 'Comment on my post'), ('like_on_my_post', 'Like on my post'), ('flag_vote_on_my_post', 'Vote on my flag post')], max_length=32),
        ),
    ]
