# Generated by Django 5.2.1 on 2025-08-24 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.hashtag'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='reposted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='posts.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_posts', to='posts.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.university'),
        ),
        migrations.AddField(
            model_name='postflagvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_votes', to='posts.post'),
        ),
        migrations.AddField(
            model_name='postflagvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postviewdaily',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_days', to='posts.post'),
        ),
        migrations.AddField(
            model_name='replyviewdaily',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_view_days', to='posts.post'),
        ),
        migrations.AddField(
            model_name='reportedpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post'),
        ),
        migrations.AddField(
            model_name='reportedpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='posts.post'),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seenpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='seenpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seenreply',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_views', to='posts.post'),
        ),
        migrations.AddField(
            model_name='seenreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votereaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.post'),
        ),
        migrations.AddField(
            model_name='votereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='posts_post_created_dadbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['university', 'created_at'], name='posts_post_univers_76b144_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['first_name'], name='posts_post_first_n_89744c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['person_age'], name='posts_post_person__eede4c_idx'),
        ),
        migrations.AddIndex(
            model_name='postflagvote',
            index=models.Index(fields=['post'], name='posts_postf_post_id_0ce06d_idx'),
        ),
        migrations.AddIndex(
            model_name='postflagvote',
            index=models.Index(fields=['user', 'post'], name='posts_postf_user_id_670561_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postflagvote',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='postviewdaily',
            index=models.Index(fields=['day'], name='posts_postv_day_c26a73_idx'),
        ),
        migrations.AddIndex(
            model_name='postviewdaily',
            index=models.Index(fields=['post', 'day'], name='posts_postv_post_id_b362e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postviewdaily',
            unique_together={('post', 'day')},
        ),
        migrations.AddIndex(
            model_name='replyviewdaily',
            index=models.Index(fields=['day'], name='posts_reply_day_f0e611_idx'),
        ),
        migrations.AddIndex(
            model_name='replyviewdaily',
            index=models.Index(fields=['reply', 'day'], name='posts_reply_reply_i_778f5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='replyviewdaily',
            unique_together={('reply', 'day')},
        ),
        migrations.AddIndex(
            model_name='reportedpost',
            index=models.Index(fields=['post'], name='posts_repor_post_id_8a38c9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportedpost',
            index=models.Index(fields=['user'], name='posts_repor_user_id_66253b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportedpost',
            index=models.Index(fields=['reason'], name='posts_repor_reason_51d888_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportedpost',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='savedpost',
            index=models.Index(fields=['user'], name='posts_saved_user_id_27a404_idx'),
        ),
        migrations.AddIndex(
            model_name='savedpost',
            index=models.Index(fields=['post'], name='posts_saved_post_id_a5f1c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedpost',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='seenpost',
            index=models.Index(fields=['post'], name='posts_seenp_post_id_0bfb4d_idx'),
        ),
        migrations.AddIndex(
            model_name='seenpost',
            index=models.Index(fields=['user', 'post'], name='posts_seenp_user_id_813ea8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seenpost',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='seenreply',
            index=models.Index(fields=['reply'], name='posts_seenr_reply_i_3060c5_idx'),
        ),
        migrations.AddIndex(
            model_name='seenreply',
            index=models.Index(fields=['user', 'reply'], name='posts_seenr_user_id_34e35d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seenreply',
            unique_together={('user', 'reply')},
        ),
        migrations.AddIndex(
            model_name='votereaction',
            index=models.Index(fields=['post'], name='posts_voter_post_id_32dcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='votereaction',
            index=models.Index(fields=['user', 'post'], name='posts_voter_user_id_93eade_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='votereaction',
            unique_together={('user', 'post')},
        ),
    ]
