# Generated by Django 5.2.1 on 2025-10-05 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('media', models.FileField(upload_to='ads/media/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('ad_type', models.CharField(choices=[('in_feed', 'In-Feed'), ('banner', 'Banner')], max_length=10)),
                ('cta_url', models.URLField(blank=True, help_text='Call-to-action URL', null=True)),
                ('target_all_universities', models.BooleanField(default=False)),
                ('duration_days', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_user_count', models.IntegerField(help_text='Number of users this ad can reach')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_universities', models.ManyToManyField(related_name='targeted_ads', to='users.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'ad_type'], name='ads_ad_status_175fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['start_date', 'end_date'], name='ads_ad_start_d_26c3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['ad', 'timestamp'], name='ads_adclick_ad_id_897e92_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['ad', 'timestamp'], name='ads_adimpre_ad_id_967dd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='adimpression',
            constraint=models.UniqueConstraint(fields=('ad', 'user', 'timestamp__date'), name='unique_daily_impression'),
        ),
    ]
